# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  host: localhost
  database: nirevent_dev
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  port: 5432
